name: CI-CD
on:
  push:
    branches: ["main"]
  workflow_dispatch: 
  
jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      # Link da documentação das actions: https://github.com/marketplace?type=actions
      - run: echo "Obtendo o codigo" 
      - name: Checkout - Obtendo o codigo #Tarefa / Etapa do fluxo
        uses: actions/checkout@v4.2.2
      - run: echo "Executar o Docker Build"
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Construção e Envio da Imagem Docker - Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./src
          push: true
          file: ./src/Dockerfile
          tags: |
            sergiobh/fake-shop:v${{ github.run_number }}
            sergiobh/fake-shop
      - run: echo "Enviar a imagem Docker para o Docker Hub"
  CD:
    needs: [CI]
    runs-on: ubuntu-latest
    steps:
      - run: echo "Obtendo o codigo" 
      - name: Checkout - Obtendo o codigo #Tarefa / Etapa do fluxo
        uses: actions/checkout@v4.2.2
      - run: echo "Configurar o Kubeconfig"
      - uses: azure/k8s-set-context@v4
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBECONFIG_DIGITALOCEN }}
      - run: echo "Executar o apply"
      - uses: Azure/k8s-deploy@v5
        with:
          manifests: |
            k8s/deployment.yaml
          images: |
            sergiobh/fake-shop:v${{ github.run_number }}
